// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "YOUR_ARDUINO_CLOUD_DEVICE_LOGIN_NAME";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onNtuChange();
void onPhChange();
void onTdsChange();

float ntu;
float ph;
float tds;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(ntu, READWRITE, ON_CHANGE, onNtuChange);
  ArduinoCloud.addProperty(ph, READWRITE, ON_CHANGE, onPhChange);
  ArduinoCloud.addProperty(tds, READWRITE, ON_CHANGE, onTdsChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
